### ISSUE TITLE
Error: undefined method `find_or_initialize_by_scrummer_caption' 

### ISSUE THREAD

**Issue by Byt3Ninja** [BadrIT/redmine_scrummer#5]
bash-4.1# rake redmine_scrummer:load_default_data
# Select language: ar, bg, bs, ca, cs, da, de, el, en, en-GB, es, et, eu, fa, fi, fr, gl, he, hr, hu, id, it, ja, ko, lt, lv, mk, mn, nl, no, pl, pt, pt-BR, ro, ru, sk, sl, sq, sr, sr-YU, sv, th, tr, uk, vi, zh, zh-TW [en] en

Error: undefined method `find_or_initialize_by_scrummer_caption' for #Class:0x7fa98e40e450
Default configuration data was not loaded.

**Comment by mahkhaled** [comment]
Are you sure you run migration successfully?

RAILS_ENV=production rake redmine:plugins:migrate

If yes, please check database. Do you have column scrummer_caption in following tables:
custom_fields
queries
roles
trackers

If yes, you can send me your database backup and I will check myself.

**Comment by Byt3Ninja** [comment]
what's the requirements to install this version of redmine 
it's will be nice if you can provide us with the real steps to install this version such as ruby required versions

**Comment by mahkhaled** [comment]
It is already listed in the README file https://github.com/BadrIT/redmine_scrummer

**Comment by Byt3Ninja** [comment]
bash-4.1# rake redmine:plugins:migrate
Migrating redmine_scrummer (Redmine Scrummer plugin)...
==  AddIsScrumToRolesAndTrackers: migrating ===================================
-- add_column(:trackers, :is_scrum, :boolean, {:default=>false})
   -> 0.1326s
-- add_column(:roles, :is_scrum, :boolean, {:default=>false})
   -> 0.0111s
==  AddIsScrumToRolesAndTrackers: migrated (0.1442s) ==========================

==  AddIsScrumIssueStatuses: migrating ========================================
-- add_column(:issue_statuses, :is_scrum, :boolean, {:default=>false})
   -> 0.0271s
==  AddIsScrumIssueStatuses: migrated (0.0274s) ===============================

==  AddTrackerShortName: migrating ============================================
-- add_column(:trackers, :short_name, :string, {:default=>""})
   -> 0.0148s
==  AddTrackerShortName: migrated (0.0150s) ===================================

==  AddIssueStatusShortName: migrating ========================================
-- add_column(:issue_statuses, :short_name, :string, {:default=>""})
   -> 0.0121s
==  AddIssueStatusShortName: migrated (0.0123s) ===============================

==  AddScrummerCaptionToQuery: migrating ======================================
-- add_column(:queries, :scrummer_caption, :string)
   -> 0.0228s
==  AddScrummerCaptionToQuery: migrated (0.0229s) =============================

==  AddScrummerCaptionToTracker: migrating ====================================
-- add_column(:trackers, :scrummer_caption, :string)
   -> 0.0573s
==  AddScrummerCaptionToTracker: migrated (0.0575s) ===========================

==  AddScrummerCaptionToIssueStatus: migrating ================================
-- add_column(:issue_statuses, :scrummer_caption, :string)
   -> 0.0144s
==  AddScrummerCaptionToIssueStatus: migrated (0.0147s) =======================

==  AddScrummerCaptionToIssueCustomField: migrating ===========================
-- add_column(:custom_fields, :scrummer_caption, :string)
   -> 0.0201s
==  AddScrummerCaptionToIssueCustomField: migrated (0.0203s) ==================

==  AddScrummerCaptionToRole: migrating =======================================
-- add_column(:roles, :scrummer_caption, :string)
   -> 0.0706s
==  AddScrummerCaptionToRole: migrated (0.0708s) ==============================

==  AddStorySizeToIssue: migrating ============================================
-- add_column(:issues, :story_size, :integer, {:default=>0})
   -> 0.0661s
==  AddStorySizeToIssue: migrated (0.0662s) ===================================

==  UpdateStorySizeToFloat: migrating =========================================
-- change_table(:issues)
   -> 0.1228s
==  UpdateStorySizeToFloat: migrated (0.1230s) ================================

==  CreateIssueHistories: migrating ===========================================
-- create_table(:issue_histories)
   -> 0.0648s
==  CreateIssueHistories: migrated (0.0649s) ==================================

==  CreateHistoryEntryForAllIssues: migrating =================================
==  CreateHistoryEntryForAllIssues: migrated (0.0000s) ========================

==  AddColumnPositionToIssues: migrating ======================================
-- add_column(:issues, :position, :integer, {:default=>0})
   -> 0.0193s
==  AddColumnPositionToIssues: migrated (0.0195s) =============================

==  CreateReleases: migrating =================================================
-- create_table(:releases)
   -> 0.0144s
==  CreateReleases: migrated (0.0146s) ========================================

==  AddReleaseIdToIssues: migrating ===========================================
-- add_column(:issues, :release_id, :integer)
   -> 0.0465s
==  AddReleaseIdToIssues: migrated (0.0467s) ==================================

==  CreatePointsHistories: migrating ==========================================
-- create_table(:points_histories)
   -> 0.0171s
==  CreatePointsHistories: migrated (0.0173s) =================================

==  AddReleaseIdToVersion: migrating ==========================================
-- add_column(:versions, :release_id, :integer)
   -> 0.0126s
==  AddReleaseIdToVersion: migrated (0.0128s) =================================

==  CreateWeeklyVacations: migrating ==========================================
-- create_table(:weekly_vacations)
   -> 0.0226s
==  CreateWeeklyVacations: migrated (0.0228s) =================================

==  CreateVacations: migrating ================================================
-- create_table(:vacations)
   -> 0.0300s
==  CreateVacations: migrated (0.0302s) =======================================

==  AddProjectIdToVacations: migrating ========================================
-- add_column(:vacations, :project_id, :integer)
   -> 0.0195s
==  AddProjectIdToVacations: migrated (0.0197s) ===============================

==  CreateScrumWeeklyNonWorkingDays: migrating ================================
-- create_table(:scrum_weekly_non_working_days)
   -> 0.0111s
==  CreateScrumWeeklyNonWorkingDays: migrated (0.0113s) =======================

==  AddRemainingHoursToIssue: migrating =======================================
-- add_column(:issues, :remaining_hours, :float)
   -> 0.0182s
==  AddRemainingHoursToIssue: migrated (0.0184s) ==============================

==  AddBusinessValueToIssue: migrating ========================================
-- add_column(:issues, :business_value, :float)
   -> 0.0976s
==  AddBusinessValueToIssue: migrated (0.0977s) ===============================

==  AddActualHoursToIssue: migrating ==========================================
-- add_column(:issues, :actual_hours, :float, {:default=>0})
   -> 0.0212s
==  AddActualHoursToIssue: migrated (0.0214s) =================================

==  AddColumnColorToTrackers: migrating =======================================
-- add_column(:trackers, :color, :string)
   -> 0.0316s
==  AddColumnColorToTrackers: migrated (0.0318s) ==============================

==  AddColorColumnToStatuses: migrating =======================================
-- add_column(:issue_statuses, :color, :string)
   -> 0.0213s
==  AddColorColumnToStatuses: migrated (0.0215s) ==============================

==  AddWidthToIssueStatus: migrating ==========================================
-- add_column(:issue_statuses, :width, :integer)
   -> 0.0308s
==  AddWidthToIssueStatus: migrated (0.0310s) =================================

==  CreateEvents: migrating ===================================================
-- create_table(:events)
   -> 0.0157s
==  CreateEvents: migrated (0.0159s) ==========================================

bash-4.1# rake redmine_scrummer:load_default_data

# Select language: ar, az, bg, bs, ca, cs, da, de, el, en, en-GB, es, et, eu, fa, fi, fr, gl, he, hr, hu, id, it, ja, ko, lt, lv, mk, mn, nl, no, pl, pt, pt-BR, ro, ru, sk, sl, sq, sr, sr-YU, sv, th, tr, uk, vi, zh, zh-TW [en] ar

Error: undefined method `each' for nil:NilClass
Default configuration data was not loaded.

in redmine 2.3.0 using BitNami

**Comment by Byt3Ninja** [comment]
Information

Redmine 2.3.0.stable

Default administrator account changed  
Attachments directory writable  
Plugin assets directory writable  
RMagick available (optional)    

Environment:
  Redmine version                          2.3.0.stable
  Ruby version                             1.9.3 (x86_64-linux)
  Rails version                            3.2.13
  Environment                              production
  Database adapter                         Mysql2
Redmine plugins:
  no plugin installed

**Comment by Byt3Ninja** [comment]
bash-4.1# rake redmine_scrummer:load_default_data --trace
(in /opt/redmine-2.3.0-0/apps/redmine/htdocs)
*\* Invoke redmine_scrummer:load_default_data (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Execute redmine_scrummer:load_default_data

# Select language: ar, az, bg, bs, ca, cs, da, de, el, en, en-GB, es, et, eu, fa, fi, fr, gl, he, hr, hu, id, it, ja, ko, lt, lv, mk, mn, nl, no, pl, pt, pt-BR, ro, ru, sk, sl, sq, sr, sr-YU, sv, th, tr, uk, vi, zh, zh-TW [en] 

rake aborted!
undefined method `each' for nil:NilClass
/opt/redmine-2.3.0-0/apps/redmine/htdocs/app/models/query.rb:310:in`available_filters'
/opt/redmine-2.3.0-0/apps/redmine/htdocs/plugins/redmine_scrummer/lib/redmine_scrummer/issue_query_patch.rb:48:in `available_filters_with_scrum_filters'
/opt/redmine-2.3.0-0/apps/redmine/htdocs/app/models/query.rb:351:in`type_for'
/opt/redmine-2.3.0-0/apps/redmine/htdocs/app/models/query.rb:217:in `block in validate_query_filters'
/opt/redmine-2.3.0-0/apps/redmine/htdocs/app/models/query.rb:215:in`each_key'
/opt/redmine-2.3.0-0/apps/redmine/htdocs/app/models/query.rb:215:in `validate_query_filters'

**Comment by Byt3Ninja** [comment]
on redmine 1.4.7.2

bash-4.1# rake db:migrate:plugins
*\* Invoke db:migrate:plugins (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
rake aborted!
uninitialized constant ActiveSupport::Concern

**Comment by mahkhaled** [comment]
Actually, redmine scrummer is not supported on redmine 2.3 It is well tested on redmine 2.1.2
I will try to check the plugin and let it works with redmine 2.3 soon.
